### ISSUE TITLE
build vars dependency?

### ISSUE THREAD

**Issue by nerdralph** [abcminiuser/dmbs#1]
Looking at gcc.mk, I couldn't find a dependency for build vars or the makefile itself.  If, for example, F_CPU is changed, will the target get rebuilt?

**Comment by nerdralph** [comment]
I cloned the repo and tested changing the makefile in the Template dir, and it rebuilt the target.  So although I can't tell how it works, it does, and therefore I'll close the issue.

**Comment by abcminiuser** [comment]
Hi nerdralph,

The makefile GCC module has its targets dependent on `$(MAKEFILE_LIST)`, so that makefile changes will force a code rebuild. This should probably be extended to all targets, but the GCC moduel is the most critical one that is affected by makefile changes the most.
