### ISSUE TITLE
Add include guard for core modules

### ISSUE THREAD

**Issue by NicoHood** [abcminiuser/dmbs#15]
If you include the core (or other) modules with other modules it should not be included again. Its a similar technique as in c header files. Its better to add the inclusion check into the core module than into your own module if you ask me. Correct me if I am wrong.

``` make
ifeq ($(findstring CORE, $(DMBS_BUILD_MODULES)),)
...
endif
```

I am willing to prepare a PR for this if you say this makes sense.

**Comment by abcminiuser** [comment]
This was previously committed in 75100beb67ec4fb4510ef1e5746e02a0279c887b, closing.
