### ISSUE TITLE
small refactoring in gcc.mk

### ISSUE THREAD

**Issue by nerdralph** [abcminiuser/dmbs#2]
I like to avoid cut/paste in code, so I suggest the following small change in gcc.mk (from line 176):
AVR8_CC_FLAGS := -mmcu=$(MCU) -fshort-enums -fno-inline-small-functions -fpack-s
truct
ifeq ($(ARCH), AVR8)
   BASE_CC_FLAGS += $(AVR8_CC_FLAGS)
else ifeq ($(ARCH), XMEGA)
   BASE_CC_FLAGS += $(AVR8_CC_FLAGS)
else ifeq ($(ARCH), UC3)

**Comment by abcminiuser** [comment]
Fixed in b770d29700bae729a03e1e37dfc540b72fd9cbb9.
