### ISSUE TITLE
OBJDIR default

### ISSUE THREAD

**Issue by nerdralph** [abcminiuser/dmbs#3]
I made two projects, both using a common library file:
SRC          = $(TARGET).c ../libs/bbuart/BBUart.S

When I build project1 then project2, it creates ../libs/bbuart/BBUart.o each time.
When I modify target.c and rebuild project1, it just relinks BBUart.o that was built with the options for project2.

My solution was to modify gcc.mk so OBJDIR defaults to objs.  This way each project directory has a separate copy of BBUart.o, built with the project-specific options.

**Comment by abcminiuser** [comment]
Good idea; fixed in https://github.com/abcminiuser/dmbs/commit/f02d9531f57c6cd1bc1b405f996ddb527455bb95.

**Comment by nerdralph** [comment]
Great, and fast response.
Now to sync my fork...
