### ISSUE TITLE
Bump AVR c++ standard to 2014

### ISSUE THREAD

**Issue by NicoHood** [abcminiuser/dmbs#31]
Wouldnt it make sense to also upgrade the c++ standart to the latest version? c++11 was required for me multiple times already. Legacy programs can still set an older outdated standard via makefile.

https://github.com/arduino/Arduino/pull/7090

Same for c standard.

**Comment by abcminiuser** [comment]
Hrm - I haven't been following the C++ implementation on the AVRs for a long time, is C++14 mature on them yet? I love using C++11, C++13 (and for a few select platforms, an early C++17 implementation) and wouldn't dream of using C++98 unless I had no other choice.

My vote would be to bump the default to C++11 as a safe baseline for various AVR toolchain versions, which gives 80% of the nice new features. If users want the other 20%, they can override the language version in their makefile.

**Comment by NicoHood** [comment]
The above linked arduino PR gives a good analysis of the current c++ implementation status. They will very likely also push to c++14, but they are on c++11 already.

It is up to you if you go to c++11 or 14, but at least update it to >=11 please :)

**Comment by abcminiuser** [comment]
Bumped the C++ default standard to C++11 in c78f60c8a8044486d7e78cea8e4e5acbff98bc94 for now - that should cover the majority of the toolchains in general use, with users being able to override to newer versions in the project files.

**Comment by AgainPsychoX** [comment]
Maybe its time to think about moving towards C++20? PTAL https://github.com/arduino/Arduino/pull/7090#issuecomment-846014769
