### ISSUE TITLE
AVRDUDE: difference between chipIDs in AVR-GCC and AVRDUDE

### ISSUE THREAD

**Issue by dudanov** [abcminiuser/dmbs#38]
In both `GCC` and `AVRDUDE` modules used one common variable - `MCU`. But this tools use different ids of the same chip. For example:
chip: `ATMega128A`
avr-gcc: `atmega128a`
avrdude: `m128`
Solving the problem could be adding to the module `AVRDUDE` it's own custom configuration file and passing them as command-line option `-C config.file` or adding AVRDUDE specific mandatory variable `AVRDUDE_PART` or `AVRDUDE_MCU`.
It is strange that this topic was not raised earlier. Or am I the only one who has come across this?

**Comment by abcminiuser** [comment]
I've merged your patch, thanks! A bit of a downer that AVRDUDE doesn't allow the actual part name as the device name to be programmed in all circumstances, but this is a decent fix for now until someone proposes to the AVRDUDE maintainers to fix their part naming.
