### ISSUE TITLE
Add documentation for creating custom DMBS modules

### ISSUE THREAD

**Issue by abcminiuser** [abcminiuser/dmbs#8]
Need to add some documentation on the core DMBS macros, and the basic module template. This will allow others to create their own DMBS modules more easily.

**Comment by eltang** [comment]
I'm preparing to write a DMBS module for the library I'm developing. I want to write it a little differently than the examples I've seen, and I wanted to check whether it's a good idea, or even possible. The makefiles of the LUFA demos are much, much simpler than they would have been without DMBS, yet I still feel that they are still too complicated for the extremely non-technical users towards whom my library is geared. Therefore, I'm thinking of encapsulating all the modules my library uses into one big module which would be the only one the makefile of a project which uses my library would need. It would perform all of the traditional functions of a module, but it would also do things a makefile would do, such as define variables for other modules to use. What do you think?

**Comment by abcminiuser** [comment]
That should work fine - DMBS was designed to be extensible, and as such you can feel free to design modules in any way you wish. Most users will only use and care about the GCC and programmer modules anyway, so making your own meta-module that encompasses those plus your own extensions would be a good idea.
